import verificaLE
le = verificaLE.LE()
le.escritorEscrevendo(1)
le.leitorBloqueado(7)
le.leitorBloqueado(6)
le.leitorBloqueado(5)
le.leitorBloqueado(4)
le.leitorBloqueado(3)
le.escritorBloqueado(2)
le.escritorSaindo(1)
le.leitorLendo(7)
le.escritorBloqueado(2)
le.leitorLendo(3)
le.leitorLendo(4)
le.leitorLendo(5)
le.leitorLendo(6)
print("Numero = 1")
print("Numero = 1")
print("Numero = 1")
print("1 e um numero impar")
print("1 e um numero impar")
le.leitorSaindo(5)
le.leitorSaindo(6)
le.leitorSaindo(7)
le.leitorSaindo(3)
le.leitorSaindo(4)
le.escritorEscrevendo(2)
le.escritorSaindo(2)
le.escritorEscrevendo(2)
le.escritorSaindo(2)
le.leitorLendo(7)
print("3 e um numero impar")
le.leitorSaindo(7)
le.escritorEscrevendo(1)
le.escritorSaindo(1)
le.leitorLendo(6)
print("4 e um numero par")
le.leitorSaindo(6)
le.escritorEscrevendo(4)
le.escritorSaindo(4)
le.leitorLendo(4)
print("Numero = 4")
le.leitorSaindo(4)
le.leitorLendo(7)
print("4 e um numero par")
le.leitorSaindo(7)
le.escritorEscrevendo(3)
le.escritorSaindo(3)
le.leitorLendo(3)
print("Numero = 3")
le.leitorSaindo(3)
le.escritorEscrevendo(2)
le.escritorSaindo(2)
le.leitorLendo(7)
print("4 e um numero par")
le.leitorSaindo(7)
le.escritorEscrevendo(1)
le.escritorSaindo(1)
le.leitorLendo(6)
print("5 e um numero impar")
le.leitorSaindo(6)
le.escritorEscrevendo(5)
le.escritorSaindo(5)
le.leitorLendo(5)
print("Numero = 5")
le.leitorSaindo(5)
le.escritorEscrevendo(3)
le.escritorSaindo(3)
le.leitorLendo(3)
print("Numero = 3")
le.leitorSaindo(3)
le.escritorEscrevendo(2)
le.escritorSaindo(2)
le.leitorLendo(7)
print("4 e um numero par")
le.leitorSaindo(7)
le.escritorEscrevendo(1)
le.escritorSaindo(1)
le.escritorEscrevendo(2)
le.escritorSaindo(2)
le.leitorLendo(6)
print("6 e um numero par")
le.leitorSaindo(6)
le.escritorEscrevendo(4)
le.escritorSaindo(4)
le.leitorLendo(4)
print("Numero = 4")
le.leitorSaindo(4)
le.leitorLendo(7)
print("4 e um numero par")
le.leitorSaindo(7)
le.escritorEscrevendo(1)
le.escritorSaindo(1)
le.escritorEscrevendo(3)
le.escritorSaindo(3)
le.leitorLendo(3)
print("Numero = 3")
le.leitorSaindo(3)
le.leitorLendo(6)
print("3 e um numero impar")
le.leitorSaindo(6)
le.escritorEscrevendo(2)
le.escritorSaindo(2)
le.leitorLendo(7)
print("4 e um numero par")
le.leitorSaindo(7)
le.escritorEscrevendo(5)
le.escritorSaindo(5)
le.leitorLendo(5)
print("Numero = 5")
le.leitorSaindo(5)
le.escritorEscrevendo(3)
le.escritorSaindo(3)
le.leitorLendo(3)
print("Numero = 3")
le.leitorSaindo(3)
le.escritorEscrevendo(1)
le.escritorSaindo(1)
le.leitorLendo(6)
print("4 e um numero par")
le.leitorSaindo(6)
